version: "3.8"
services:
  # Сервис для вашего Java-приложения с использованием Maven
  jira_project2_back:
    container_name: jira_project2_back
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - bridge
    ports:
      - "6543:8080"

networks:
  bridge:
