CREATE TABLE IF NOT EXISTS board
(
    id              bigint          GENERATED BY DEFAULT AS IDENTITY,
    title           varchar         NOT NULL,
    date            timestamp(6)    NOT NULL,
    picture         varchar,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS usr
(
    id              bigint          GENERATED BY DEFAULT AS IDENTITY,
    email           varchar         NOT NULL,
    password        varchar         NOT NULL,
    name            varchar         NOT NULL,
    surname         varchar         NOT NULL,
    position        varchar,
--     refresh_token   varchar         NOT NULL,
--     temp_password   varchar         NOT NULL,
    profile_picture varchar,
--     UNIQUE(email, refresh_token),
    UNIQUE(email),
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS board_to_users
(
    id              bigint          GENERATED BY DEFAULT AS IDENTITY,
    board_id        bigint,
    user_id         bigint,
    role            varchar         NOT NULL,
    verified        boolean         DEFAULT false,
    PRIMARY KEY(id),
    FOREIGN KEY(board_id) REFERENCES board(id) ON DELETE CASCADE,
    FOREIGN KEY(user_id) REFERENCES usr(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS clmn
(
    id              bigint          GENERATED BY DEFAULT AS IDENTITY,
    title           varchar         NOT NULL,
    board_id        bigint          NOT NULL,
    column_order    int             NOT NULL,
    UNIQUE(title, column_order),
    PRIMARY KEY(id),
    FOREIGN KEY(board_id) REFERENCES board(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS task
(
    id              bigint          GENERATED BY DEFAULT AS IDENTITY,
    title           varchar         NOT NULL,
    description     varchar,
    column_id       bigint          NOT NULL,
    author_id       bigint          NOT NULL,
    executor_id     bigint          NOT NULL,
    parent_task_id  bigint,
    date            timestamp(6)    NOT NULL,
    completed_date  timestamp(6)    DEFAULT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(column_id) REFERENCES clmn(id) ON DELETE CASCADE,
    FOREIGN KEY(executor_id) REFERENCES usr(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notification_table
(
    id              bigint          GENERATED BY DEFAULT AS IDENTITY,
    date            timestamp(6)    NOT NULL,
    is_read         boolean         DEFAULT false,
    message         varchar         NOT NULL,
    type            smallint        NOT NULL,
    user_id         bigint,
    PRIMARY KEY(id),
    FOREIGN KEY(user_id) REFERENCES usr(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS verify_token
(
    id              bigint          GENERATED BY DEFAULT AS IDENTITY,
    token_value     varchar         NOT NULL,
    expiration_time timestamp(6)    NOT NULL,
    UNIQUE(token_value),
    PRIMARY KEY(id)
)